# Numpy - Numerical Python

## 1.Why Learn NumPy?
## what is it?
    Numpy is a powerful python library for numerical computations. it provides fast and memory efficient multi-dimenional arrays.
## why we need it?
    1.pure python lists are slow for large datasets.
    2.Numpy arrays are optimized for speed and vectorized operations
    3.Most Data Science and Machine Learning libraries (like pandas,scikit-learn ,Tensorflow ) are built in top of Numpy
## Where is it used?
    1.Data Analysis
    2.Machine Learning and Deep Learning
    3.Image processing (OpenCV ,PIL use Numpy arrays)
    4.Scientific Computing and Simulations
    

In [ ]:
import  numpy as np
import sys
print(sys.executable)

c:\Users\Bhavani\OneDrive\Documents\python_basic-0109\venv\python.exe


In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
## 2.Importing Numpy

import numpy as np
## 3.Arrays Vs Python Lists
import numpy as np
import time
#python list
py_list=[i for i in range (1000000)]
#numpy array
np_array=np.arange(1000000)
#Time comparion
start_time=time.time()
sum(py_list)
print("Python list sum time:",time.time()-start_time)
start=time.time()
np.sum(np_array)
print("Numpy array sum time:",time.time()-start_time)


Python list sum time: 0.019943714141845703
Numpy array sum time: 0.019943714141845703


Creating Arrays

1.np.arange(start,stop,step)
purpose:Creates an array of numbers starting from start up to but not including stop ,incremented by step.

In [4]:
ar=np.arange(0,10,2)
print(ar)

[0 2 4 6 8]


2.np.linespace(start,stop,num)
purpose:Creates an array of num equally spaced numbers between start and stop(inclusive)


In [ ]:
ar=np.linspace(0,1,3)
print(ar)
#3 numbers evenly spaced


[0.  0.5 1. ]


In [7]:
#from list
arr=np.array([1,2,3,4,5])
print("Array:",arr)
#Zeros and Ones
print("Zeros:",np.zeros((2,3)))
print("Ones:",np.ones((2,3)))
#Range and Linespace
print("Aranage:",np.arange(0,10,2))
print("Linespace:",np.linspace(0,1,5))


Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Aranage: [0 2 4 6 8]
Linespace: [0.   0.25 0.5  0.75 1.  ]


In [8]:
###5 Array Properties
arr=np.array([[1,2,3,4],[5,21,4,1]])
print("Array Shape",arr.shape)
print("Array dtype:",arr.dtype)
print("Array Size:",arr.size)
print("Array ndim:",arr.ndim)


Array Shape (2, 4)
Array dtype: int64
Array Size: 8
Array ndim: 2


In [10]:
### 6. Indexing and slicing
arr=np.array([10,20,30,40,50])
print("Element at index 2:",arr[2])
print("Element from  index 1 to 3",arr[1:4])
print("Element at indices 0,2,4:",arr[[0,2,4]])
print("Every second element:",arr[::2])
print("Reversed array:",arr[::-1])


Element at index 2: 30
Element from  index 1 to 3 [20 30 40]
Element at indices 0,2,4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [11]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix shape: (3, 3)
Matrix dtype: int64
Matrix size: 9
Matrix ndim: 2
2
[4 5 6]
[3 6 9]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]
Mean of all elements: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]
Element-wise multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [12]:
## 7. Operations and Broadcasting
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


In [13]:
## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)


In [14]:
#array of 3x3 matrix from values 1 to  9
arr=np.arange(1,10)
reshaped=arr.reshape(3,3)
print("Array:",reshaped)
print("Second row",reshaped[1,:])

Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row [4 5 6]


In [15]:
### find mean ,median , and standard deviation of [12,15,20,25,30]
arr=np.array([12,15,20,25,30])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("std:",np.std(arr))


Mean: 20.4
Median: 20.0
std: 6.529931086925803


In [16]:
### Generate a random 5X5 matrix and find its maximum and minimum values
#(Hint :Use np.random.rand for random numbers)
matrix=np.random.rand(5,5)
print("Random 5 X 5 Matrix:\n",matrix)
max=np.max(matrix)
print("\nMaximum Value:",max)
min=np.min(matrix)
print("\nMinimum Value:",min)


Random 5 X 5 Matrix:
 [[0.62316286 0.50662067 0.33984598 0.11644294 0.01532933]
 [0.20483444 0.28965776 0.90957583 0.95562728 0.85354128]
 [0.0487553  0.83803245 0.38103247 0.96408036 0.08189746]
 [0.85510603 0.40241757 0.50591262 0.54935983 0.555587  ]
 [0.32174789 0.02301758 0.77788532 0.00560048 0.06910839]]

Maximum Value: 0.9640803625887722

Minimum Value: 0.005600476384589381
